package ru.mirea.infinitejourneysbackend.domain.model;

public enum Country {
    USA,
    Spain,
    France,
    China,
    Italy,
    Turkey,
    Germany,
    United_Kingdom,
    Mexico,
    Thailand,
    Austria,
    Malaysia,
    Canada,
    Japan,
    Russia,
    Portugal,
    Greece,
    Saudi_Arabia,
    Australia,
    South_Korea,
    India,
    United_Arab_Emirates,
    Egypt,
    Singapore,
    Vietnam,
    Indonesia,
    Netherlands,
    Switzerland,
    Philippines,
    Brazil
}
